name = "Achtertuin"
version = "6.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abb015035910a7b493c8d7eb7ec3ad5a8eb8825e14011e9c3a9911c4344aca24"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
