name = "Achtertuin"
version = "6.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59b4a498d1251ce61474f945b5691e7a0e5b7b8fd7ba823e4fedc88100e6f081"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
